### ISSUE TITLE
define code style guidelines

### ISSUE THREAD

**Issue by Trolldemorted** [ENOFLAG/ENOKEY#38]
We should agree on a code style and create an [editorconfig](https://editorconfig.org/)

**Comment by fsck** [comment]
I would propose to use the default rustfmt and integrate that into our CI-workflow. It is also supported in popular editors so we do not need to add any extra files to the repository. Would that be fine with everybody?

**Comment by Trolldemorted** [comment]
rustfmt is step forward, but it does not solve all problems:

- it does not cover non-rust files (markdown, html, ...) (?)
- it does not define or enforce a correct line feed (?)
- it is supported by only a handful of editors

**Comment by fsck** [comment]
> rustfmt is step forward, but it does not solve all problems:
> 
>     * it does not cover non-rust files (markdown, html, ...) (?)
Do we currently have an issue with format mismatches on other files?
> 
>     * it does not define or enforce a correct line feed (?)
[It does](https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#newline_style) (close enough for me):
```
Auto (default):
The newline style is detected automatically on a per-file basis. Files with mixed line endings will be converted to the first detected line ending style.
```
> 
>     * it is supported by only a handful of editors
Rustfmt is the offical rust-lang solution and available as a standalone tool for CI and local use as well. The big editors are supporting both solutions anyway as far as I can tell

Overall I am really not so concerned about formatting at this stage and therefore would not want to micromanage it. Rustfmt seems easy enough, because it has sensible rust defaults. Editorconfig would require bikeshedding the formatting itself.

**Comment by Trolldemorted** [comment]
>Do we currently have an issue with format mismatches on other files?

That depends on what you consider an issue - e.g. we are using 2 whitespaces intents in our html files, but my editors don't care because they can't know. Same goes for the hbs templates, shellscripts, and so on.

>It does (close enough for me):

If I have to create a file, it will have windows linefeeds. Unless you add a `.rustfmt.toml` they will keep their windows linefeeds, at least as lomg everyone is running rustfmt before committing and no one touches the first line break.

>Editorconfig would require bikeshedding the formatting itself.

Editorconfig is not about high-level formatting, it is more a "for each file with this file extension, use this encoding, use these linefeeds, this indentation when the user presses tab, do (not) enforce a trailing newline" guideline.

**Comment by fsck** [comment]
> > Do we currently have an issue with format mismatches on other files?
> 
> That depends on what you consider an issue - e.g. we are using 2 whitespaces intents in our html files, but my editors don't care because they can't know. Same goes for the hbs templates, shellscripts, and so on.

I would question your editor then. Mine are detecting the indentation just fine and acting accordingly.
> 
> > It does (close enough for me):
> 
> If I have to create a file, it will have windows linefeeds. Unless you add a `.rustfmt.toml` they will keep their windows linefeeds, at least as lomg everyone is running rustfmt before committing and no one touches the first line break.

I would expect any contributor to make the sane choice and contribute in line with the other files in the repo. Otherwise we can still sort this out in the pull request.
> 
> > Editorconfig would require bikeshedding the formatting itself.
> 
> Editorconfig is not about high-level formatting, it is more a "for each file with this file extension, use this encoding, use these linefeeds, this indentation when the user presses tab, do (not) enforce a trailing newline" guideline.

Exactly that is the problem. Discussing the issue of tabs vs. spaces alone will take ages. I do not want to do low-level formatting or make decisions upon it. I just want to conform to **the standard**.

**Comment by Trolldemorted** [comment]
>I would question your editor then. Mine are detecting the indentation just fine and acting accordingly.

The only editor I have that does it is visual studio code, all others don't. Which editors are you using?

>I would expect any contributor to make the sane choice and contribute in line with the other files in the repo.

I am sorry, but I will not use `file` or similar tools to determine the wanted line feeds of every project I am working on. If a project wants a certain type of line feeds, it should have an editorconfig, and my editors will comply ¯\\_(ツ)_/¯

>Exactly that is the problem. Discussing the issue of tabs vs. spaces alone will take ages. I do not want to do low-level formatting or make decisions upon it. I just want to conform to the standard.

You obviously already have decided you want 2/4 whitepaces, LFs, unicode and no trailing newlines - the only difference would be making this de-facto standard official, and automatically used by most editors.

Many editors have weird defaults - e.g. any file touched by nano will always have a trailing newline because reasons. Imho you can't blame the users, but you can take preventive measures spurious changes like dis- and reappearing trailing newlines don't clutter your commits.

**Comment by fsck** [comment]
> > I would question your editor then. Mine are detecting the indentation just fine and acting accordingly.
> 
> The only editor I have that does it is visual studio code, all others don't. Which editors are you using?

I am using sublime and intellij. Both are working fine.
I just tested gedit, which is not detecting it. 
Sublime and Gedit are not supporting .editorconfig out of the box.
> 
> > I would expect any contributor to make the sane choice and contribute in line with the other files in the repo.
> 
> I am sorry, but I will not use `file` or similar tools to determine the wanted line feeds of every project I am working on. If a project wants a certain type of line feeds, it should have an editorconfig, and my editors will comply ¯\_(ツ)_/¯

Yours will, because you selected this and configured plugins. The next person has made a different selection of editor and/or formatingfile and they will want a different config file.
> 
> > Exactly that is the problem. Discussing the issue of tabs vs. spaces alone will take ages. I do not want to do low-level formatting or make decisions upon it. I just want to conform to the standard.
> 
> You obviously already have decided you want 2/4 whitepaces, LFs, unicode and no trailing newlines - the only difference would be making this de-facto standard official, and automatically used by most editors.

Not really, I believe the two whitespaces come from the example from the rocket repository. I am perfectly happy to change that to reflect the way the rust code is formatted.
LFs are probably due to the way cargo initializes a project, but also the OS default for me. So I do not know if that would be different on Windows.
No trailing newlines: literally never thought about that one.
> 
> Many editors have weird defaults - e.g. any file touched by nano will always have a trailing newline because reasons. Imho you can't blame the users, but you can take preventive measures spurious changes like dis- and reappearing trailing newlines don't clutter your commits.

I am not particularly against having an editorconfig file, if you have a usecase. I just do not want to have an indepth discussions about the content and I do not want to have to force contributors to install unnecessary software plugins. I am just not sure if you are actually wanting to discuss coding style or just want to push this editorconfig project. Maybe we are just talking about different things here.

If we can find an editorconfig, which formalizes the default rustfmt config or some other standard, than I do not have a problem adding that to the repository.

**Comment by fsck** [comment]
I updated #44 to include the .editorconfig used in the clippy project. Would that be acceptable to everyone? Do we need to include checking in CI? I feel like the CI story on editorconfig is not well documented.

**Comment by Trolldemorted** [comment]
>I am using sublime and intellij. Both are working fine.

To be fair, intellij is an IDE, not an editor.

>Not really, I believe the two whitespaces come from the example from the rocket repository. I am perfectly happy to change that to reflect the way the rust code is formatted.

👍
Should our sample dc-yaml use 4 whitespaces too? I am not a yaml expert, no clue what you are supposed to use.

>LFs are probably due to the way cargo initializes a project, but also the OS default for me. So I do not know if that would be different on Windows.

Editors on windows use CRLF by default, and I assume on macOS they will use CR.

>I am just not sure if you are actually wanting to discuss coding style or just want to push this editorconfig project. Maybe we are just talking about different things here.

I don't want to push editorconfig (or any competition), I just have had very annoying experiences in projects where different contributors used different operating systems, and different encodings, line feeds and trails were spread through the entire codebase.


>I updated #44 to include the .editorconfig used in the clippy project. Would that be acceptable to everyone? Do we need to include checking in CI? I feel like the CI story on editorconfig is not well documented.

👍
If we could, we imo should, but I don't know whether or how easy we can.

**Comment by fsck** [comment]
> Should our sample dc-yaml use 4 whitespaces too? I am not a yaml expert, no clue what you are supposed to use.

Sure, why not.

> > I updated #44 to include the .editorconfig used in the clippy project. Would that be acceptable to everyone? Do we need to include checking in CI? I feel like the CI story on editorconfig is not well documented.
> 
> +1
> If we could, we imo should, but I don't know whether or how easy we can.

As I was saying. It does not look very promising unless you are a fan of experimental npm tools.

**Comment by domenukk** [comment]
> Editors on windows use CRLF by default, and I assume on macOS they will use CR. 

All editors but notepad.exe can adapt. 
I've settled for \n for all files since most commandline tools I use expect it. I would suggest linefeed file endings for any project.
Windows user can still use git's aweful line ending translation feature when checking out...

**Comment by fsck** [comment]
> > Editors on windows use CRLF by default, and I assume on macOS they will use CR.
> 
> All editors but notepad.exe can adapt.

Even [notepad](https://blogs.msdn.microsoft.com/commandline/2018/05/08/extended-eol-in-notepad/) supports it now

**Comment by Trolldemorted** [comment]
I stand corrected - npp and notepad indeed continue with the initial line feeds. Nice!

**Comment by parafoxx** [comment]
> I stand corrected - npp and notepad indeed continue with the initial line feeds. Nice!

A good editor (most) continue to use whatever is already used. New files are still a problem then.

> Editors on windows use CRLF by default, and I assume on macOS they will use CR.

Mac switched their OS line endings to LF years ago (since Mac OS X is out). In consideration that even notepad.exe is now able to use LF I would go for that as our default. 

About using an _.editorconfig_, I am not really against it but looking on their website I dont see many editors supporting it out-of-the-box. Many still need an extension to honor such a file or might not even support it all!
